info_cooldown: 10s
info_bar:
  - "&#a25a5aЖители &rи &#1b63c6странствующие торговцы &rбудут следовать за игроком с &aизумрудным блоком &rв руках"
  - "Один поршень может сдвинуть &c64 &rблока"
  - "Не хочешь видеть через &5порталы&r? Пиши &c/seeportal"
  - "Чтобы писать в глобальный чат поставь &e! &rперед сообщением"
  - "Чтобы сидеть пиши &c/sit"
  - "Чтобы лежать пиши &c/lay"
  - "Чтобы ползти пиши &c/crawl"
  - "Чтобы крутиться пиши &c/spin"
  - "На сервре доступна команда &c/skin"
  - "Сервер поддерживает мод &cEmoteCraft&r. Советуем поставить!"
  - "Чтобы поменять пароль пиши &c/changepass"
  - "Житель &5священник &rможет собирать &4незерский нарост"
  - "&dЭндермены &rне будут атаковать игроков с надетой &5головой дракона"
  - "Новые механизмы - &c/nova items"
  - "Включить/выключить функцию WAILA - &c/nova waila on/off"