info_cooldown: 10s
info_bar:
  - "<#a25a5a>Жители <white>и <#1b63c6>странствующие торговцы <white>будут следовать за игроком с <green>изумрудным блоком <white>в руках"
  - "Один поршень может сдвинуть <red>64 <white>блока"
  - "Не хочешь видеть через <dark_purple>порталы&r? Пиши <red>/seeportal"
  - "Чтобы писать в глобальный чат поставь <yellow>! <white>перед сообщением"
  - "Чтобы сидеть пиши <red>/sit"
  - "Чтобы лежать пиши <red>/lay"
  - "Чтобы ползти пиши <red>/crawl"
  - "Чтобы крутиться пиши <red>/spin"
  - "На сервре доступна команда <red>/skin"
  - "Сервер поддерживает мод <red>EmoteCraft<white>. Советуем поставить!"
  - "Чтобы поменять пароль пиши <red>/changepassword"
  - "Житель <dark_purple>священник <white>может собирать <dark_red>незерский нарост"
  - "<light_purple>Эндермены <white>не будут атаковать игроков с надетой <dark_purple>головой дракона"
  - "Новые механизмы - <red>/nova items"
  - "Включить/выключить функцию WAILA - <red>/nova waila on/off"
  - "Выключить/включить этот боссбар - <red>/infobar"