cooldown: 5s

header:
  - "<#6fa8dc>Gidra"
  - "<gradient:aqua:light_purple>Бесконечное приключение</gradient>"
  - "<gold>Пинг: <proc[colored_ping]>"
  - "%end%"

footer:
  - ""
  - " <gray>TPS: <proc[colored_tps]>   <gold>|   <gray>MSPT: <proc[colored_mspt]> "
  - "%end%"