space_replacer: "-"

Столярный-Верстак:
  - armor_stand:
    input1: smooth_stone_slab
    input2: <item[stick].with[quantity=6]>
    result: armor_stand

  - statuette:
    input1: smooth_stone_slab
    input2: <item[stick].with[quantity=3]>
    result: <server.flag[statuette]>

  - stand_with_arms:
    input1: armor_stand
    input2: <item[redstone_torch].with[quantity=2]>
    result: <server.flag[stand_with_arms]>

  - stand_with_arms:
    input1: <server.flag[statuette]>
    input2: redstone_torch
    result: <server.flag[statuette_with_arms]>

Скупщик:
  - алмаз:
    input1: diamond
    result: <item[silver_coin]>
  - золото:
    input1: raw_gold
    result: <item[bronze_coin].with[quantity=8]>
  - железо:
    input1: raw_iron
    result: <item[bronze_coin].with[quantity=6]>
  - медь:
    input1: <item[raw_copper].with[quantity=4]>
    result: <item[bronze_coin]>
  - уголь:
    input1: <item[coal].with[quantity=2]>
    result: <item[bronze_coin]>
  - обсидиан:
    input1: obsidian
    result: <item[bronze_coin]>

Шахтёр:
  - алмаз:
    input1: <item[silver_coin]>
    result: diamond
  - золото:
    input1: <item[bronze_coin].with[quantity=8]>
    result: raw_gold
  - железо:
    input1: <item[bronze_coin].with[quantity=6]>
    result: raw_iron
  - медь:
    input1: <item[bronze_coin]>
    result: <item[raw_copper].with[quantity=4]>
  - уголь:
    input1: <item[bronze_coin]>
    result: <item[coal].with[quantity=2]>
  - обсидиан:
    input1: <item[bronze_coin]>
    result: obsidian

Коллекционер:
  - разблокиратор_команд:
    input1: <item[gold_coin]>
    result: <item[trades_cmd_unblocker]>
  - древний_город:
    input1: <item[silver_coin].with[quantity=13]>
    result: <item[ancient_chest]>
  - джунглиевый_храм:
    input1: <item[silver_coin].with[quantity=2]>
    result: <item[jungle_chest]>
  - земля_картина:
    input1: <item[silver_coin]>
    result: <item[earth_painting]>
  - ветер_картина:
    input1: <item[silver_coin]>
    result: <item[wind_painting]>
  - вода_картина:
    input1: <item[silver_coin]>
    result: <item[water_painting]>
  - огонь_картина:
    input1: <item[silver_coin]>
    result: <item[fire_painting]>
  - лампа:
    input1: <item[silver_coin]>
    result: <item[lit_redstone_lamp]>
  - печь:
    input1: <item[silver_coin]>
    result: <item[lit_furnace]>
  - коптильня:
    input1: <item[silver_coin]>
    result: <item[lit_smoker]>
  - плавильная_печь:
    input1: <item[silver_coin]>
    result: <item[lit_blast_furnace]>
  - бочка:
    input1: <item[silver_coin]>
    result: <item[opened_barrel]>
  - катализатор:
    input1: <item[silver_coin].with[quantity=3]>
    result: <item[bloom_catalyst]>